=== b3e3e3/horseys/data/skill.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "$defs": {
        "stat": {
            "type": "object",
            "additionalProperties": {
                "oneOf": [
                    {
                        "type": "number"
                    },
                    {
                        "type": "object",
                        "properties": {
                            "min": {
                                "type": "number"
                            },
                            "max": {
                                "type": "number"
                            }
                        },
                        "required": [
                            "min",
                            "max"
                        ]
                    }
                ]
            }
        }
    },
    "type": "object",
    "properties": {
        "version": {
            "type": "integer"
        },
        "name": {
            "type": "string"
        },
        "wit_effectiveness": {
            "type": "number"
        },
        "conditions": {
            "type": "object",
            "properties": {
                "phase": {
                    "type": "string",
                    "enum": [
                        "EARLY",
                        "MID",
                        "LATE",
                        "FINAL",
                        "FINISH"
                    ]
                }
            },
            "additionalProperties": false
        },
        "effects": {
            "type": "object",
            "properties": {
                "boost": {
                    "$ref": "#/$defs/stat"
                }
            }
        }
    },
    "required": [
        "$schema",
        "version",
        "name",
        "wit_effectiveness",
        "conditions",
        "effects"
    ]
}

=== b3e3e3/horseys/data/skills/horse_maneuver.json
{
    "$schema": "../skill.schema.json",
    "version": 1,
    "name": "Horse Maneuver",
    "wit_effectiveness": 1.0,
    "conditions": {
        "phase": "MID"
    },
    "effects": {
        "boost": {
            "speed": {
                "min": 50.0,
                "max": 100.0
            }
        }
    }
}
